# Generated by Django 2.1 on 2018-09-08 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algodao',
            fields=[
                ('idAl', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('peso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiadora',
            fields=[
                ('idBen', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('producaoDiaria', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstoqueAlgodao',
            fields=[
                ('idEstoque', models.AutoField(primary_key=True, serialize=False)),
                ('dtEntrada', models.DateTimeField(auto_now_add=True)),
                ('qtde', models.IntegerField()),
                ('Algodao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAlgodao.Algodao')),
            ],
        ),
        migrations.CreateModel(
            name='Fazenda',
            fields=[
                ('idFaz', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('logradouro', models.CharField(max_length=150)),
                ('CNPJ', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('idProd', models.AutoField(primary_key=True, serialize=False)),
                ('dtEntrada', models.DateTimeField(auto_now_add=True)),
                ('Beneficiadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAlgodao.Beneficiadora')),
                ('EstoqueAlgodao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAlgodao.EstoqueAlgodao')),
            ],
        ),
        migrations.AddField(
            model_name='estoquealgodao',
            name='Fazenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloAlgodao.Fazenda'),
        ),
    ]
