# Generated by Django 2.1 on 2018-09-08 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloAlgodao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estoquealgodao',
            old_name='Fazenda',
            new_name='fazenda',
        ),
        migrations.RenameField(
            model_name='producao',
            old_name='Beneficiadora',
            new_name='beneficiadora',
        ),
        migrations.RenameField(
            model_name='producao',
            old_name='EstoqueAlgodao',
            new_name='estoqueAlgodao',
        ),
    ]
