# Generated by Django 2.1 on 2018-09-08 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloAlgodao', '0002_auto_20180907_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fazenda',
            name='CNPJ',
        ),
        migrations.RemoveField(
            model_name='fazenda',
            name='logradouro',
        ),
    ]
