# Generated by Django 2.1 on 2018-09-09 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloAlgodao', '0004_auto_20180908_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estoquealgodao',
            old_name='Algodao',
            new_name='algodaoTipo',
        ),
    ]
